### ISSUE TITLE
Bom Submission

### ISSUE THREAD

**Issue by timChase98** [idibona27/pedometer#1]
@idibona27 Did you ever update you BOM after we met?

**Comment by idibona27** [comment]
yes! it is under releases with an updated version as the .xlsx and .csv. I did decide to keep the external frequency oscillator in case I use the board for any other purposes in the future and I believe I added the necessary capacitors.

**Comment by idibona27** [comment]
[BOM.xlsx](https://github.com/idibona27/pedometer/files/5398017/BOM.xlsx)

I cannot post the .csv here, but it is in the release

**Comment by idibona27** [comment]
pushed @timChase98

**Comment by timChase98** [comment]
Looks good
