### ISSUE TITLE
Schematic Submission

### ISSUE THREAD

**Issue by timChase98** [idibona27/pedometer#2]
- [x] Schematics should have clear flow from left-right 
  - [x] Power input top left
  - [x] Inputs to uController middle left 
  - [x] uController in the center
  - [x] uController outputs to right  
- [x] There should be a 100nF decoupling cap accross the power pins on all ICs 
- [x] C17, C18, C19 should all be decoupling the signal to gnd not in series with the signal
- [x] Pin 1 on the 327 has both a NC and a connection to GND
- [x] What are you trying to do with the power to the 327? 
- [ ] Do you have two independent and different color power LEDs? 
- [ ] How does power get onto the board? 

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by idibona27** [comment]
thank you Tim I will make all revisions and re-submit. I was trying to make a voltage divider like I did in my prototype for the power going to the 327, I may need a voltage regulator instead. The no connection to the 327 that I have going to ground I believe can be fixed, its an optional ground or no connection (the IC has so many NC but two NC are optional ground pins) but the NC was the way that I found the library for the 327. The power I was going to sent to a jumper from my battery pack which was connected to all of the +5V markers. again, I will make all revisions and push the new changes thank you for feedback.

**Comment by timChase98** [comment]
I would definitely go with the regulator path.  Your board looks really good though.  I don't have any negative feedback there.  I think if you go with the internal oscillator you might find that your layout goes a bit easier as the crystal is by far your largest component.  You also have a few spots where the silk screen is a little close to the edge of the board.

**Comment by idibona27** [comment]
pushed, thank you so much. Gerber submission release is version_2 and schematic submission release is version_3, all files are also under version control

**Comment by timChase98** [comment]
- [ ] 3.3 should be a flag not a named net
- [ ] Add the power LED in parallel to the regulator not in series 
- [ ] AVCC should connect to 5V 
- [ ] AREF should connect to 5V and have a decoupling capacitor 
- [ ] you need a pull up resistor on the reset line 

Additionally what battery are you planning on using?

**Comment by idibona27** [comment]
okay I have made schematic changes and am currently re-doing my board. I plan on using two +3V coin cell batteries in series.

**Comment by timChase98** [comment]
Schematic gets a pass.  Good job.

**Comment by idibona27** [comment]
thank you!
