### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by timChase98** [idibona27/pedometer#3]
This looks really good.  I don't see any changes you need to make to the copper layers or component placement.  You do have quite a few spots where the silkscreen overlaps pads, all of these need to be fixed.  I would suggest toggling high contrast mode (Thats what its called in kicad.  I think it's called single layer in eagle) to help highlight the silkscreen layer without having to focus on all the other layers at the same time.  Your fiducials are also showing up on the board outline layer for some reason.  this also needs to be fixed.

**Comment by idibona27** [comment]
thank you! with regards to the silkscreen overlap, my image is on the bottom layer and I cannot see where it may be overlapping pads even after changing to single view. should I just eliminate the bottom image for simplification? also I am unsure which layer to place the fiducials, I had them placed on the top layer far from the board outline so I am confused why this would be happening. thanks again!

![checkSilk](https://user-images.githubusercontent.com/72680029/98863827-ef816280-2436-11eb-8134-1a50eda41447.PNG)

**Comment by idibona27** [comment]
okay I think I had component names overlapping on the top layer with pads, also unsure why holes are going onto dimension layer. Is it okay if I do not use holes and instead place my monkey in the orientation of the board? I have tried placing holes multiple ways and cannot get them off of the outline layer.

**Comment by timChase98** [comment]
The images were not the issue, and I will be very disappointed if you remove the monkey ( as it is the only thing holding my sanity together at the moment). The issue was with the names on the top layer.  Are you trying to add mounting holes or fiducials?

**Comment by idibona27** [comment]
I love the monkey also I refuse to remove that form of sanity from either of us. I am trying to add fiducials for reference but no matter the layer I place them on, they end up on the dimension layer -_- I have tried placing them on the top, on the hole layer, on the bottom just because and nothing changes this

**Comment by timChase98** [comment]
What library are you using for the fiducials? I think the 388 Library and the adafruit library have the correct ones.

**Comment by idibona27** [comment]
how would I access those libraries? I did not know they existed I was using the hole feature on the board layout

**Comment by idibona27** [comment]
I did find the libraries in the m drive and believe I have pushed all changes, incremented new releases and added all files to renders.

**Comment by timChase98** [comment]
You might have to increase the stroke width on the monkey.  Min from the board house is .15mm.  There's also a star on top of the pads of C9.

**Comment by idibona27** [comment]
can you send a screenshot of the star I cannot see it on my end, also I think that will make monkey too big I don't think he can fit but I will try

**Comment by idibona27** [comment]
I found the star and changed the footprint (all set), currently working with monkey pal.. sorry for so many messages!

**Comment by idibona27** [comment]
tysm for your help!! closing issue

**Comment by timChase98** [comment]
Your board was sent to fab.  I think deep down you already knew this though

**Comment by idibona27** [comment]
a little, still extremely exciting. thank you for all your help!
